config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'bookings/new'
  get 'bookings/create'
  get 'bookings/destroy'
  get 'pages/contant'
  get 'pages/services'
  get 'pages/about'
  devise_for :users
  resources :posts
  resources :listings do
  member do
    post 'create_picture'
  end
end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # config/routes.rb

resources :pictures, only: [:index, :show, :new, :create, :edit, :update, :destroy]

   root "posts#index"
  
resources :users do
  member do
    put 'update_profile_image'
  end
end

resources :pictures do
  member do
    post 'like'
    delete 'unlike'
  end
end



 put 'users/update_profile_image', to: 'users#update_profile_image', as: 'update_profile_image'
 resources :reviews
  resources :listings, only: [:show, :edit], as: :listing
  resources :bookings, only: [:new, :create, :destroy]
  get 'about', to: 'pages#about'
  get 'services', to: 'pages#services'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'contact#create'
  get '/search', to: 'search#index', as: 'search'
  get '/explore', to: 'explore#index', as: 'explore'
  delete '/signout', to: 'sessions#destroy', as: :signout
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/contact_message.rb
class ContactMessage < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :pictures, dependent: :destroy
  # ...
end

app/models/message.rb
class Message < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :subject, presence: true
  validates :content, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
     has_many :bookings
      has_many :likes, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image

end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
 def gravatar_url(size = 200)
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end

   has_many :galleries
  has_one_attached :profile_image
   has_many :likes, dependent: :destroy

  def likes?(picture)
  likes.exists?(picture_id: picture.id)
end

  # Method to get the user's profile image
  def display_profile_image
    if profile_image.attached?
      profile_image
    else
      # Return a default image or placeholder if no image is attached
      'default_profile_image.jpg'
    end
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
   def new
    @booking = Booking.new
    @pictures = Picture.all
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to root_path, notice: 'Booking successfully created.'
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :picture_id, :date)
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contant
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def post_params
    params.require(:post).permit(:title, :content, :image)
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :keyword, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/bookings/create.html.erb
<!-- app/views/bookings/create.html.erb -->

<h1>Booking Confirmation</h1>

<div class="alert alert-success">
  Your booking has been successfully created.
</div>

<h2>Booked Picture Details</h2>

<div class="card">
  <%= image_tag @booking.picture.image, class: 'card-img-top' %>
  <div class="card-body">
    <h5 class="card-title"><%= @booking.picture.title %></h5>
    <p class="card-text"><%= @booking.picture.description %></p>
    <p class="card-text"><%= @booking.picture.amount %></p>
    <p>Booking Date and Time: <%= @booking.date.strftime('%Y-%m-%d %H:%M') %></p>
  </div>
</div>

<p>
  <%= link_to 'Back to Pictures', pictures_path, class: 'btn btn-primary' %>
</p>

app/views/bookings/destroy.html.erb
<!-- app/views/bookings/destroy.html.erb -->

<h1>Booking Cancellation</h1>

<div class="alert alert-danger">
  Your booking has been canceled.
</div>

<h2>Canceled Booking Details</h2>

<div class="card">
  <%= image_tag @booking.picture.image, class: 'card-img-top' %>
  <div class="card-body">
    <h5 class="card-title"><%= @booking.picture.title %></h5>
    <p class="card-text"><%= @booking.picture.description %></p>
    <p class="card-text"><%= @booking.picture.amount %></p>
    <p>Booking Date and Time: <%= @booking.date.strftime('%Y-%m-%d %H:%M') %></p>
  </div>
</div>

<p>
  <%= link_to 'Back to Pictures', pictures_path, class: 'btn btn-primary' %>
</p>

app/views/bookings/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center">Book a Home</h1>

      <%= form_with(model: @booking, url: bookings_path, method: :post) do |form| %>
        <div class="form-group">
          <%= form.label :picture_id, 'Select a Picture' %>
          <%= form.collection_select(:picture_id, @pictures, :id, :title, { prompt: 'Select a picture' }, class: 'form-control') %>
        </div>

        <div class="form-group">
          <%= form.label :date, 'Booking Date and Time' %>
          <%= form.datetime_select :date, { class: 'form-control' } %>
        </div>

        <div class="text-center">
          <%= form.submit 'Book Picture', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>